### ISSUE TITLE
希望增加NEXA中转！

### ISSUE THREAD

**Issue by 0xUaena** [EvilGenius-dot/RustMinerSystem#3]

**Comment by 0xUaena** [comment]
请求支持NEXA的支持，NEXA现在也是矿工喜欢的热门币种，pool.kryptex.com作为第一大算力池，虽然POOL域名可以访问，但是挖矿服务器nexa.kryptex.network是被屏蔽的，希望作者能支持！

**Comment by EvilGenius-dot** [comment]
> 请求支持NEXA的支持，NEXA现在也是矿工喜欢的热门币种，pool.kryptex.com作为第一大算力池，虽然POOL域名可以访问，但是挖矿服务器nexa.kryptex.network是被屏蔽的，希望作者能支持！

收到

**Comment by EvilGenius-dot** [comment]
> 请求支持NEXA的支持，NEXA现在也是矿工喜欢的热门币种，pool.kryptex.com作为第一大算力池，虽然POOL域名可以访问，但是挖矿服务器nexa.kryptex.network是被屏蔽的，希望作者能支持！

下个版本添加
